/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sources.AutoCompletion;

import Sources.PROPRIETE;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Gateway
 */
public class PanelAuto extends javax.swing.JPanel {

    /**
     * Creates new form PanelAuto
     */
    
    DialAuto dialog = null;
    PROPRIETE prop = null;
    AutocompleteJComboBox auto;
    public static int Xsouris = 0;
    public static int Ysouris = 0;
    private ImageIcon icone = null;
    
    
    public PanelAuto(AutocompleteJComboBox auto) {
        initComponents();
        this.auto = auto;
    }
    
    public void setDialogueEtListe(List<String> myWords, PROPRIETE prop){
        this.dialog = new DialAuto(new javax.swing.JFrame(), true, myWords, icone);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        Xsouris = ((int)dim.getWidth()/2)+300;
        Ysouris = ((int)dim.getHeight()/2)-100;
        dialog.setTitle(prop.getNom()+" - Recherche");
        this.prop = prop;
        AfficherComboAuto(Xsouris, Ysouris);
    }
    
    public void setImage(ImageIcon icone){
        this.icone = icone;
        this.jLabel1.setIcon(icone);
    }
    
    public void setCouleurs(Color arriere, Color avant){
        this.setBackground(arriere);
        this.jLabel1.setForeground(avant);
    }
    
    public Object getSeletedItem(){
        return this.dialog.getSeletedItem();
    }
    
    public void setCouleurTexte(Color col){
        this.jLabel1.setForeground(col);
    }

    private void AfficherComboAuto(int x, int y) {
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                dialog.dispose();
            }
        });
        dialog.setBounds(x-dialog.getWidth(), y, 400, 95);
        dialog.setVisible(true);
        if(dialog.getSeletedItem() == null){
            jLabel1.setText(prop.getValeurs().firstElement()+"");
        }else{
            jLabel1.setText(dialog.getSeletedItem()+"");
        }
        prop.setValeurSelectionne(dialog.getSeletedItem());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Objet Séléctionné");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        AfficherComboAuto(evt.getXOnScreen(), evt.getYOnScreen());
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
